### ISSUE TITLE
Had fight at dinner table

### ISSUE THREAD

**Issue by r-ym** [Elapache98/Tip-ulator-1.0#8]
Hello,

I tried to use TipUlator at  dinner, but most people had fairly asymmetric orders. A friend who ordered a burger got into it with another who order lamb chops since he was expected to contribute equally. I certainly understand his qualms and was hoping the next release could account for this.

Sincerely,

**Comment by Elapache98** [comment]
<img width="757" alt="Screenshot 2023-07-23 at 10 51 51 PM" src="https://github.com/Elapache98/Tip-ulator-1.0/assets/86984626/c89f9999-5856-4ef7-9f11-da4114f22d33">

**Comment by r-ym** [comment]
Closing since main contributor seems indifferent to the users
